server:
  port: 8081
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /spring-boot-test
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
 endpoints:
  web:
   exposure:
    include: "*"

spring:
  application:
    name: eureka-1
    freemarker:
      prefer-file-system-access: false
      cache: false
  datasource:
      druid:
        db-type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.56.125.94:3306/spring-boot-test?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf-8
        username: root
        password: Wang@67420
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        filter:
          commons-log:
            connection-logger-name: stat,wall,log4j
          stat:
              log-slow-sql: true
              slow-sql-millis: 2000
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-data-source-stat: true
  freemarker:
    checkTemplateLocation: false
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    #json 时间戳统一转换
    jackson:
      date-format:   yyyy-MM-dd HH:mm:ss
      time-zone:   GMT+8
    aop:
      proxy-target-class: true
    mvc:
      static-path-pattern: /**
    resource:
      static-locations: classpath:/static/,classpath:/public/
    autoconfigure:
      exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #redis 配置
#  redis:
#    database: 0
#    host: 127.0.0.1
#    lettuce:
#      pool:
#        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
#        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
#        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
#      shutdown-timeout: 100ms
#    password: ''
#    port: 6379
logging:
#  config: classpath:log4j2.yml
  level:
    org.jeecg.modules.system.mapper : debug
#Mybatis输出sql日志
mybatis:
  config-locations:classpath: com/spring/rock/mybatis-config.xml
  mybatis.mapper-locations: classpath:com/spring/rock/mappers/*.xml
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#ribbon:
#  eureka:
#    enabled: true
#cas单点登录
#cas:
#  prefixUrl: http://cas.example.org:8443/cas
